//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMentor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMentor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ שיעור אינו תקין.
        /// </summary>
        internal static string CLIP_FILE_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("CLIP_FILE_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השיעור נשמר בהצלחה !.
        /// </summary>
        internal static string CLIP_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CLIP_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [סוף].
        /// </summary>
        internal static string END_PAUSE_SECTION_ANCHOR {
            get {
                return ResourceManager.GetString("END_PAUSE_SECTION_ANCHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart MyMentor to apply changes.
        /// </summary>
        internal static string ENGLISH_CHANGE_LANGUAGE {
            get {
                return ResourceManager.GetString("ENGLISH_CHANGE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השיעור לא נשמר מהשינויים האחרונים. האם אתה בטוח לצאת?.
        /// </summary>
        internal static string EXIT_CONFIRM {
            get {
                return ResourceManager.GetString("EXIT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך תפוגה חייב להיות גדול מהיום.
        /// </summary>
        internal static string EXPIRED_DATE_ERROR {
            get {
                return ResourceManager.GetString("EXPIRED_DATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיעור זה נוצר ע&apos;&apos;י משתמש אחר, לפי תנאי השימוש לא ניתן לערוך או לצפות בסטודיו בשיעורים שנוצרו על ידי משתמש אחר.
        /// </summary>
        internal static string FINGERPRINT_ERROR {
            get {
                return ResourceManager.GetString("FINGERPRINT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לצאת ולהכנס מהמערכת על מנת להחיל את השינויים.
        /// </summary>
        internal static string HEBREW_CHANGE_LANGUAGE {
            get {
                return ResourceManager.GetString("HEBREW_CHANGE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנך מחובר כ -.
        /// </summary>
        internal static string LOGIN_AS {
            get {
                return ResourceManager.GetString("LOGIN_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להכנס מחדש למערכת אחרי הפעלה מחודשת.
        /// </summary>
        internal static string LOGIN_OTHER_USER {
            get {
                return ResourceManager.GetString("LOGIN_OTHER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש למלא שדות חובה למאפייני השיעור.
        /// </summary>
        internal static string MANDATORY_FIELDS {
            get {
                return ResourceManager.GetString("MANDATORY_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק מעבר זה ואת הבאים אחריו.
        /// </summary>
        internal static string MENU_REMOVE_ANCHORS {
            get {
                return ResourceManager.GetString("MENU_REMOVE_ANCHORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר מינ&apos;.
        /// </summary>
        internal static string MIN_PRICE {
            get {
                return ResourceManager.GetString("MIN_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר השיעור קטן מהמינימום המותר לסוג זה.
        /// </summary>
        internal static string MIN_PRICE_ERROR {
            get {
                return ResourceManager.GetString("MIN_PRICE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדבק.
        /// </summary>
        internal static string MNU_PASTE {
            get {
                return ResourceManager.GetString("MNU_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדבק במצב הוספה.
        /// </summary>
        internal static string MNU_PASTE_APPEND_MODE {
            get {
                return ResourceManager.GetString("MNU_PASTE_APPEND_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיימת הקלטה לביצוע תזמון.
        /// </summary>
        internal static string NO_AUDIO_EXISTS {
            get {
                return ResourceManager.GetString("NO_AUDIO_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים קובץ שמע בזיכרון, האם בכל זאת ליצור חדש ?.
        /// </summary>
        internal static string OVERWRITE_AUDIO_CONFIRM {
            get {
                return ResourceManager.GetString("OVERWRITE_AUDIO_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השהה.
        /// </summary>
        internal static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם אתה בטוח להסיר את התזמונים לשיעור זה ?.
        /// </summary>
        internal static string REMOVE_SCHEDULING_CONFIRM {
            get {
                return ResourceManager.GetString("REMOVE_SCHEDULING_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לבחור לפחות אפשרות עוגן אחת.
        /// </summary>
        internal static string SOURCE_NEED_TO_SELECT_OPTION {
            get {
                return ResourceManager.GetString("SOURCE_NEED_TO_SELECT_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירה לא חוקית.
        /// </summary>
        internal static string SOURCE_UNLEGAL_OPTION {
            get {
                return ResourceManager.GetString("SOURCE_UNLEGAL_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [התחלה].
        /// </summary>
        internal static string START_PAUSE_SECTION_ANCHOR {
            get {
                return ResourceManager.GetString("START_PAUSE_SECTION_ANCHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עצור.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיעור ללא שם.
        /// </summary>
        internal static string UNTITLED_CLIP {
            get {
                return ResourceManager.GetString("UNTITLED_CLIP", resourceCulture);
            }
        }
    }
}
